### ISSUE TITLE
Horovod does not compile with old framework versions that setup.py accept

### ISSUE THREAD

**Issue by EnricoMi** [horovod/horovod#3453]
Building Horovod, the log says:

But actually building Horovod against PyTorch 1.2.0, it fails with:

```
    /tmp/pip-req-build-13fs79hx/horovod/torch/mpi_ops_v2.cc:61:12: error: ‘class at::Tensor’ has no member named ‘floor_divide_’
         tensor.floor_divide_(divisor);
                ^~~~~~~~~~~~~
```

Looks like the minimum PyTorch that Horovod compiles with is 1.5.0.

**Comment by EnricoMi** [comment]
The same holds for `mxnet==1.4.0`:

```
  /tmp/pip-req-build-i02msprl/horovod/mxnet/mpi_ops.cc:393:5: error: ‘MXEnginePushAsync’ was not declared in this scope
       MXEnginePushAsync(DoHorovodOperation, ops_param, DeleteMpiOpsParam,
       ^~~~~~~~~~~~~~~~~
```

It works with `mxnet==1.4.1` (https://github.com/apache/incubator-mxnet/pull/14770).
