### PR TITLE
Docker: Restrict numpy<1.24.0 for pandas<1.1.0, h5py<3.0, mxnet

### LINKED ISSUE #3804: CI: Builds fail with Numpy 1.24
Builds with Python versions newer than 3.7 fail because Numpy have changed their API in release 1.24 and some package requirements aren't restrictive enough.

https://github.com/horovod/horovod/actions/runs/3837009090
```
# ...
2023-01-03T19:09:52.2227909Z #29 28.83   File "/usr/local/lib/python3.8/dist-packages/pandas/_testing.py", line 24, in <module>
2023-01-03T19:09:52.2228233Z #29 28.83     import pandas._libs.testing as _testing
2023-01-03T19:09:52.2228836Z #29 28.83   File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
2023-01-03T19:09:52.2229288Z #29 28.83   File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
2023-01-03T19:09:52.2229635Z #29 28.83     raise AttributeError("module {!r} has no attribute "
2023-01-03T19:09:52.2230033Z #29 28.83 AttributeError: module 'numpy' has no attribute 'bool'
```

### PR DESCRIPTION
**Pull request by maxhgerlach**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes #3804

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by maxhgerlach** [comment]
This fixes building all test images. 

Going forward it will be good to find a nicer solution (i.e., update dependencies) so we will be able to test with Numpy 0.24+ in the future.

In the latest run of [Build and Test heads (test-cpu-openmpi-gloo-py3_8-tfhead-keras_none-torchhead-mxnethead-pyspark3_3_1)](https://github.com/horovod/horovod/actions/runs/3846096170/jobs/6552838801#logs) there was a failure 3x with `test_ray_elastic.py::test_fault_tolerance_hosts_added_and_removed`, but I suppose that's flakiness. The previous CI pipeline run for this PR was fine there.

**Review by nvcastet — APPROVED** [review]

**Review by EnricoMi — APPROVED** [review]
