### ISSUE TITLE
Installation failures following 0.24 release

### ISSUE THREAD

**Issue by ananthsub** [horovod/horovod#3449]
PyTorch Lightning is seeing CI failures, seemingly correlated with the timing of the 0.24 release. 

Example PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/12083
CI job: https://github.com/PyTorchLightning/pytorch-lightning/runs/5426958866?check_suite_focus=true
Last parts of stacktrace:
```
      /usr/bin/c++ -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0  -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -O3 -g -DNDEBUG  -Wl,--version-script=/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/horovod.lds -Wl,-Bsymbolic-functions -Wl,-z,relro,-z,now -shared -Wl,-soname,mpi_lib_v2.cpython-38-x86_64-linux-gnu.so -o ../../../../lib.linux-x86_64-3.8/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so CMakeFiles/pytorch.dir/__/common/common.cc.o CMakeFiles/pytorch.dir/__/common/controller.cc.o CMakeFiles/pytorch.dir/__/common/fusion_buffer_manager.cc.o CMakeFiles/pytorch.dir/__/common/group_table.cc.o CMakeFiles/pytorch.dir/__/common/half.cc.o CMakeFiles/pytorch.dir/__/common/logging.cc.o CMakeFiles/pytorch.dir/__/common/message.cc.o CMakeFiles/pytorch.dir/__/common/operations.cc.o CMakeFiles/pytorch.dir/__/common/parameter_manager.cc.o CMakeFiles/pytorch.dir/__/common/process_set.cc.o CMakeFiles/pytorch.dir/__/common/response_cache.cc.o CMakeFiles/pytorch.dir/__/common/stall_inspector.cc.o CMakeFiles/pytorch.dir/__/common/thread_pool.cc.o CMakeFiles/pytorch.dir/__/common/timeline.cc.o CMakeFiles/pytorch.dir/__/common/tensor_queue.cc.o CMakeFiles/pytorch.dir/__/common/ops/collective_operations.cc.o CMakeFiles/pytorch.dir/__/common/ops/operation_manager.cc.o CMakeFiles/pytorch.dir/__/common/optim/bayesian_optimization.cc.o CMakeFiles/pytorch.dir/__/common/optim/gaussian_process.cc.o CMakeFiles/pytorch.dir/__/common/utils/env_parser.cc.o CMakeFiles/pytorch.dir/__/common/ops/cuda_operations.cc.o CMakeFiles/pytorch.dir/__/common/ops/gpu_operations.cc.o CMakeFiles/pytorch.dir/__/common/ops/nccl_operations.cc.o CMakeFiles/pytorch.dir/__/common/nvtx_op_range.cc.o CMakeFiles/pytorch.dir/__/common/gloo/gloo_context.cc.o CMakeFiles/pytorch.dir/__/common/gloo/gloo_controller.cc.o CMakeFiles/pytorch.dir/__/common/gloo/http_store.cc.o CMakeFiles/pytorch.dir/__/common/gloo/memory_store.cc.o CMakeFiles/pytorch.dir/__/common/ops/gloo_operations.cc.o CMakeFiles/pytorch.dir/handle_manager.cc.o CMakeFiles/pytorch.dir/ready_event.cc.o CMakeFiles/pytorch.dir/cuda_util.cc.o CMakeFiles/pytorch.dir/mpi_ops_v2.cc.o CMakeFiles/pytorch.dir/adapter_v2.cc.o CMakeFiles/pytorch.dir/cmake_device_link.o   -L/usr/local/cuda/targets/x86_64-linux/lib  -Wl,-rpath,/root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib:/usr/local/cuda/lib64 /usr/lib/x86_64-linux-gnu/libnccl_static.a -ldl /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libc10.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libtorch.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libtorch_python.so /usr/local/cuda/lib64/libcudart.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libc10_cuda.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so /root/miniconda3/envs/lightning/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so ../../third_party/compatible_gloo/gloo/libcompatible_gloo.a ../common/ops/cuda/libcompatible_horovod_cuda_kernels.a -lpthread -lcudadevrt -lcudart_static -lrt -lpthread -ldl
      /usr/bin/ld: ../common/ops/cuda/libcompatible_horovod_cuda_kernels.a(cuda_kernels.cu.o): relocation R_X86_64_PC32 against symbol `_ZTISt11logic_error@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
      /usr/bin/ld: final link failed: bad value
      collect2: error: ld returned 1 exit status
      make[2]: *** [horovod/torch/CMakeFiles/pytorch.dir/build.make:686: ../../lib.linux-x86_64-3.8/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so] Error 1
      make[2]: Leaving directory '/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/build/temp.linux-x86_64-3.8/RelWithDebInfo'
      make[1]: *** [CMakeFiles/Makefile2:467: horovod/torch/CMakeFiles/pytorch.dir/all] Error 2
      make[1]: Leaving directory '/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/build/temp.linux-x86_64-3.8/RelWithDebInfo'
      make: *** [Makefile:130: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/setup.py", line 209, in <module>
          setup(name='horovod',
        File "/root/miniconda3/envs/lightning/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/lightning/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/lightning/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/root/miniconda3/envs/lightning/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/setup.py", line 144, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/root/miniconda3/envs/lightning/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', 'VERBOSE=1']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> horovod

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Error: Process completed with exit code 1.
```

**Comment by chongxiaoc** [comment]
Can you try 0.24.1? https://github.com/horovod/horovod/releases/tag/v0.24.1
It comes with a NVCC patch in CMake.

**Comment by Borda** [comment]
@awaelchli ^^ :rabbit:

**Comment by EnricoMi** [comment]
@maxhgerlach

**Comment by maxhgerlach** [comment]
0.24.1 should not make a difference here, that was just a convenience fix for the CMake stage.

@ananthsub, would it be possible to provide us with an easy to reproduce setup to look into this? E.g.: pull this container, then execute that command line to try and install Horovod.

**Comment by maxhgerlach** [comment]
I could gather from your log that `-fPIC` is indeed not passed to the compiler when building that object file:
```
cd /tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/build/temp.linux-x86_64-3.8/RelWithDebInfo/horovod/common/ops/cuda && /usr/local/cuda/bin/nvcc -ccbin=/usr/bin/c++ -DEIGEN_MPL2_ONLY=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_NCCL=1 -DHAVE_NVTX=1 -DHOROVOD_GPU_ALLGATHER=78 -DHOROVOD_GPU_ALLREDUCE=78 -DHOROVOD_GPU_ALLTOALL=78 -DHOROVOD_GPU_BROADCAST=78 -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/HTTPRequest/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/assert/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/config/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/core/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/detail/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/iterator/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/lockfree/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/mpl/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/parameter/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/predef/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/preprocessor/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/static_assert/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/type_traits/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/boost/utility/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/lbfgs/include -I/tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/third_party/gloo  -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -x cu -dc /tmp/pip-install-zgvz2e58/horovod_5695a6f66c0544858137cfaf9082e7b4/horovod/common/ops/cuda/cuda_kernels.cu -o CMakeFiles/compatible_horovod_cuda_kernels.dir/cuda_kernels.cu.o
```

But it is in our CI, for example in this run https://github.com/horovod/horovod/runs/5413572228?check_suite_focus=true:
```
2022-03-03T22:30:41.4085411Z #44 41.43   cd /tmp/pip-req-build-6m_nlje5/build/temp.linux-x86_64-3.8/RelWithDebInfo/horovod/common/ops/cuda && /usr/local/cuda/bin/nvcc -ccbin=/usr/bin/c++ -DEIGEN_MPL2_ONLY=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_NCCL=1 -DHAVE_NVTX=1 -DHOROVOD_GPU_ALLGATHER=78 -DHOROVOD_GPU_ALLREDUCE=78 -DHOROVOD_GPU_ALLTOALL=78 -DHOROVOD_GPU_BROADCAST=78 -I/tmp/pip-req-build-6m_nlje5/third_party/HTTPRequest/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/assert/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/config/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/core/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/detail/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/iterator/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/lockfree/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/mpl/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/parameter/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/predef/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/preprocessor/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/static_assert/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/type_traits/include -I/tmp/pip-req-build-6m_nlje5/third_party/boost/utility/include -I/tmp/pip-req-build-6m_nlje5/third_party/lbfgs/include -I/tmp/pip-req-build-6m_nlje5/third_party/gloo  -O3 -Xcompiler -fPIC -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_53,code=sm_53 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_72,code=sm_72 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -x cu -dc /tmp/pip-req-build-6m_nlje5/horovod/common/ops/cuda/cuda_kernels.cu -o CMakeFiles/compatible_horovod_cuda_kernels.dir/cuda_kernels.cu.o
```

**Comment by maxhgerlach** [comment]
Which is weird as it _should_ be hardcoded.

https://github.com/horovod/horovod/blob/a5edcd02b7501066834ec9748bf1d7337eea2a8e/horovod/common/ops/cuda/CMakeLists.txt#L2

https://github.com/horovod/horovod/blob/a5edcd02b7501066834ec9748bf1d7337eea2a8e/cmake/build_utils.py#L94

**Comment by maxhgerlach** [comment]
So somehow the environment variable `HOROVOD_BUILD_CUDA_CC_LIST` now has `;` to separate values there while we expect `,`. I don't think that part changed with 0.24.0 though. The documentation also shows commas: https://horovod.readthedocs.io/en/stable/install_include.html#environment-variables

@ananthsub, looks like you must recently have changed how you configure that variable?

**Comment by maxhgerlach** [comment]
> Any suggestion about building with release candidate PT1.11?
https://github.com/PyTorchLightning/pytorch-lightning/runs/5437550540?check_suite_focus=true

Error in the log
> 2022-03-06T08:28:51.3948625Z       /tmp/pip-install-ex2wdjmy/horovod_2d792a0df11241b1b1a0dab729eab029/horovod/torch/cuda_util.cc:18:10: fatal error: THC/THC.h: No such file or directory
2022-03-06T08:28:51.3948744Z          18 | #include <THC/THC.h>
2022-03-06T08:28:51.3948845Z             |          ^~~~~~~~~~~

I believe that should be fixed in Horovod 0.24 -- earlier versions won't build with recent PyTorch.

**Comment by EnricoMi** [comment]
@Borda can you confirm Horovod 0.24.1 works for you?

As a side note: Horovod tests against PyTorch nightly, which works just fine.

Interestingly, that is currently `1.12.0.dev20220308+cpu`: https://github.com/horovod/horovod/runs/5466454308?check_suite_focus=true#step:10:11121

**Comment by EnricoMi** [comment]
Looks like Horovod master builds with `torch==1.11.0+cpu`: https://github.com/horovod/horovod/runs/5494443563?check_suite_focus=true#step:10:10011

**Comment by EnricoMi** [comment]
And it looks like it builds with `torch==1.11.0+cu113` as well:
https://github.com/horovod/horovod/runs/5495439432?check_suite_focus=true#step:7:2451
