### ISSUE TITLE
pyarrow 0.17 changed hdfs.connect api to remove driver parameter

### ISSUE THREAD

**Issue by tgravescs** [horovod/horovod#2000]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Keras Estimator example
2. Framework version:
3. Horovod version:  master branch
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

Trying to run with the latest horovod code with pyarrow 0.17.1 against HDFS for the working directory and it fails with:

```
Traceback (most recent call last):
  File "keras_spark_rossmann_estimator.py", line 408, in <module>
    store = Store.create(args.work_dir)
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/store.py", line 141, in create
    return HDFSStore(prefix_path, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/store.py", line 337, in __init__
    self._hdfs = self._get_filesystem_fn()()
  File "/usr/local/lib/python3.8/dist-packages/horovod/spark/common/store.py", line 416, in fn
    return pa.hdfs.connect(**hdfs_kwargs)
TypeError: connect() got an unexpected keyword argument 'driver'
```

It looks like pyarrow removed that parameter with commit:
https://github.com/apache/arrow/commit/4e53749097ba687afd5e000067925def2e2802c9#diff-72abd78694ddde2b1a059b194978b77b

Note I called it like:
python keras_spark_rossmann_estimator.py --num-proc 2 --batch-size 1000 --epochs 2 --master spark://3ee9bf36f06b:7077 --work-dir hdfs:///rossmann

**Comment by tgravescs** [comment]
Note this is setup here: https://github.com/horovod/horovod/blob/master/horovod/spark/common/store.py#L335

**Comment by tgravescs** [comment]
it looks like the older version of pyarrow may also only support Hadoop 2.x. Its failing with class mismatch exception when I run on hdfs 3.x.  I see they have a new api for filesystems, not sure if that supports both

**Comment by tgaddair** [comment]
Thanks for the detailed report @tgravescs.  Can you try #2003 and verify whether it fixes the issue?

**Comment by tgravescs** [comment]
so I tried a similar patch myself, but I think it failed with petastorm also using the parameter. I don't have the error around to show the trace.
I tried using older version of  pyarrow which gets around this error but then fails to work with Hadoop 3.1.3, looks like Hadoop version mismatch.

**Comment by tgaddair** [comment]
Let me see if I can get a fix in to Petastorm for this.

**Comment by tgaddair** [comment]
@tgravescs can you similarly try installing petastorm from [this](https://github.com/uber/petastorm/pull/556) PR and see if it unblocks the issue?

**Comment by tgravescs** [comment]
giving it a try

**Comment by tgravescs** [comment]
so those 2 patches lets me use pyarrow 0.17.1 I can't access hdfs still. It looks like a version mismatch issue - either with protobuf or Hadoop versions. I'm not sure if its just an issue with my setup or something in the docker file build.

**Comment by tgaddair** [comment]
@tgravescs can you share the error message in a gist or pastebin?

**Comment by tgravescs** [comment]
https://gist.github.com/tgravescs/1d825fc334b9c03bda540616e6718125

**Comment by tgaddair** [comment]
Thanks, seems this is a classpath issue of some kind, according to sources online (https://stackoverflow.com/questions/49808271/java-lang-classcastexception-cannot-be-cast-to-com-google-protobuf-message).  Did you make any additional modifications to the Docker image for Spark 3?

**Comment by tgravescs** [comment]
the only difference is the docker image uses the newest version of Spark built against Hadoop 3.1, then running on yarn 3.1 includes the Hadoop jars and such from Yarn.  Those are all 3.1 jars though.  It really looks like its a protobuf mismatch but I haven't been able to track it exactly.  I see tensor flow pulls a version of protobuf but not sure.

**Comment by tgaddair** [comment]
Yes, TensorFlow's imported version of protobuf is a frequent problem (#686).  Are you using TensorFlow 2.2?  They're using Protobuf 3.8 (https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/workspace.bzl#L475).

There are some [suggestions](https://stackoverflow.com/questions/46235376/tensorflow-protobuf-version-mismatch) here to deal with it.

**Comment by tgravescs** [comment]
yes tensor flow 2.2.

I was hoping tensor flow had fixed with https://github.com/tensorflow/ecosystem/pull/30/files but looks like that is only the tensorflow-hadoop package. looks like Hadoop 3.3 will update protobuf but that isn't out yet: https://issues.apache.org/jira/browse/HADOOP-16557

You must not run this on hdfs at this point because I assume it doesn't work with Hadoop 2.x either?

**Comment by tgravescs** [comment]
I'll try to write small test program to narrow it down and see if that is really the issue

**Comment by tgravescs** [comment]
ok so I wrote a small program in a clean environment without horovod and tried different hdfs setups and it appears pyarrow connectivity works with Hadoop 2.x but gives the error above with 3.x

**Comment by tgaddair** [comment]
Thanks for verifying, @tgravescs.  We'll go ahead and land the fix, then.
