### ISSUE TITLE
CI: Builds fail with Numpy 1.24

### ISSUE THREAD

**Issue by maxhgerlach** [horovod/horovod#3804]
Builds with Python versions newer than 3.7 fail because Numpy have changed their API in release 1.24 and some package requirements aren't restrictive enough.

https://github.com/horovod/horovod/actions/runs/3837009090
```
# ...
2023-01-03T19:09:52.2227909Z #29 28.83   File "/usr/local/lib/python3.8/dist-packages/pandas/_testing.py", line 24, in <module>
2023-01-03T19:09:52.2228233Z #29 28.83     import pandas._libs.testing as _testing
2023-01-03T19:09:52.2228836Z #29 28.83   File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
2023-01-03T19:09:52.2229288Z #29 28.83   File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
2023-01-03T19:09:52.2229635Z #29 28.83     raise AttributeError("module {!r} has no attribute "
2023-01-03T19:09:52.2230033Z #29 28.83 AttributeError: module 'numpy' has no attribute 'bool'
```

**Comment by maxhgerlach** [comment]
In Horovod we refer to `numpy.bool` in one place that might need to be updated, too: https://github.com/horovod/horovod/blob/f99dfbf84db6e1dc4ae929d7666e988004247cd6/horovod/spark/common/util.py#L98
