### ISSUE TITLE
Make Horovod work with petastorm >= 0.11.0

### ISSUE THREAD

**Issue by EnricoMi** [horovod/horovod#2909]
With release `0.11.0` of petastorm, constructor of `BatchedDataLoader` has changed, which breaks torch `RemoteTrainer`:

```
[0]<stderr>:Traceback (most recent call last):
[0]<stderr>:  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[0]<stderr>:    "__main__", mod_spec)
[0]<stderr>:  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
[0]<stderr>:    exec(code, run_globals)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/spark/task/gloo_exec_fn.py", line 30, in <module>
[0]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/spark/task/gloo_exec_fn.py", line 23, in main
[0]<stderr>:    task_exec(driver_addresses, settings, 'HOROVOD_RANK', 'HOROVOD_LOCAL_RANK')
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/spark/task/__init__.py", line 61, in task_exec
[0]<stderr>:    result = fn(*args, **kwargs)
[0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/spark/torch/remote.py", line 250, in train
[0]<stderr>:    inmemory_cache_all=inmemory_cache_all)
[0]<stderr>:TypeError: __init__() got an unexpected keyword argument 'num_epochs'
```

Thus we have limited petastorm version to pre `0.11.0` (see #2829).

Make `RemoteTrainer` work with both, pre and post `0.11.0`, or move to post `0.11.0` and require `petastorm>=0.11.0`, whatever is more reasonable.

**Comment by EnricoMi** [comment]
@chongxiaoc interested?

**Comment by chongxiaoc** [comment]
Will change in the rebase of #2896

**Comment by chongxiaoc** [comment]
Actually it already passes tests with v0.11.0rc6

**Comment by EnricoMi** [comment]
> Actually it already passes tests with v0.11.0rc6

So 0.11.0rc6 is backward-compatible but 0.11.0 release is not?

**Comment by EnricoMi** [comment]
I am happy with #2896 closing this when merged.

**Comment by EnricoMi** [comment]
@chongxiaoc thanks for looking into this!

**Comment by tgaddair** [comment]
Fixed by #2896.
