### PR TITLE
Fix model loading: use custom scope

### PR DESCRIPTION
**Pull request by liangz1**
## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description
This issue is introduced by #2234 .
Add custom scope when loading the saved model on the worker.
Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

### CODE REVIEW

**Comment by tgaddair** [comment]
Looks like there are some test failures:

```

# test dbfs_store.read_serialized_keras_model
--
  | get_dbfs_output_dir = dbfs_store.get_local_output_dir_fn("0")
  | with get_dbfs_output_dir() as run_output_dir:
  | dbfs_ckpt_path = run_output_dir + "/" + local_store.get_checkpoint_filename()
  | if LooseVersion(tensorflow.__version__) < LooseVersion("2.0.0"):
  | model.save_weights(dbfs_ckpt_path)
  | else:
  | model.save(dbfs_ckpt_path)
  | >           serialized_model_dbfs = dbfs_store.read_serialized_keras_model(dbfs_ckpt_path, model)
  | E           TypeError: read_serialized_keras_model() missing 1 required positional argument: 'custom_objects'


```

**Comment by tgaddair** [comment]
@liangz1 is this ready for review?

**Comment by liangz1** [comment]
@tgaddair Yes, please.

**Review by tgaddair — APPROVED** [review]
LGTM!
